#!/bin/bash
conda list | tail -n+3 | awk '{print $1, $2, "Anaconda"}' > temp.info
brew list --versions | awk '{print $0, "Homebrew"}'>> temp.info
julia --version | awk '{print $1, $3, "User_Install"}' >> temp.info
rtg version | head -1 | awk '{print $2, $5, "User_Install"}' >> temp.info
column -t temp.info | sort -u --ignore-case
rm temp.info
printf "\n"
R -e 'installed.packages(fields = c("Package", "Version"))[,c("Package", "Version")]' | tail -n+22 | grep -v '^>' | awk '{print $1, $3, "R_package"}' | perl -pe 's/"//g' | sort -u --ignore-case | column -t
